- name: copy prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    desc: /opt/prometheus/prometheus.yml


- name: Restart the service prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Copy Alert Manager Config
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml

- name: Restart Alertmanager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted
